apiVersion: apps/v1
kind: Deployment
metadata:
  name: icecast-nrksuper-proxy
  labels:
    app: icecast-nrksuper-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: icecast-nrksuper-proxy
  template:
    metadata:
      labels:
        app: icecast-nrksuper-proxy
    spec:
      containers:
      - name: icecast-nrksuper-proxy
        image: jorgenwahlberg/docker-icecast-nrksuper-proxy:0.9.3
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: icecast-nrksuper-proxy
  name: icecast-nrksuper-proxy-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: icecast-nrksuper-proxy
  type: LoadBalancer
